### ISSUE TITLE
[Question]: Questions about app

### ISSUE THREAD

**Issue by bi4key** [shubham0204/SmolChat-Android#8]
1. When chat generate response and show token speed ( example 14.50 tokens/s ) . If I close app and open app again then tokens disappeared. This is normal? Because other app leave all info about that, and that stats don't disappeared.

---

2. How is default values of this options:

A) Context size? (How big is context size of chat conversation)

B) n_predict? (How long is max response of chat generate)

---

3. In future this options/values from (2 point) will be editable somewhere in options?

**Comment by shubham0204** [comment]
> 1. When chat generate response and show token speed ( example 14.50 tokens/s ) . If I close app and open app again then tokens disappeared. This is normal? Because other app leave all info about that, and that stats don't disappeared.

Yes, this is the intended behaviour. The token generation speeds are not being persisted in the local database. The speed is only displayed for the last chat message generated by the LLM/SLM. I did not see any value being added by persisting the token generation speed for each LLM generated message. If you feel storing the speed for each message can be helpful for users, do let me know.

> How is default values of this options:
> A) Context size? (How big is context size of chat conversation)
>
> B) n_predict? (How long is max response of chat generate)

The context size is currently fixed at `2048`. See [`LLMInference::load_model`](https://github.com/shubham0204/SmolChat-Android/blob/ad77888d357eeb16d26b12dc60d5023e3bb7af1f/smollm/src/main/cpp/llm_inference.cpp#L12). Using `-1` for `ctx_params.n_ctx` resulted in some errors when loading some models (-1 indicates that llama.cpp will assume the context length provided in the GGUF file)

We do not use `n_predict`, instead we use `llama_token_is_eog` to check for an EOG (end-of-generation) token to be produced.

> 3. In future this options/values from (2 point) will be editable somewhere in options?

Yes sure! Adding more parameters for customization will be great for some *power* users who need fine-grain control over the LLM's response generation.
